### ISSUE TITLE
Mouse move down

### ISSUE THREAD

**Issue by imkrey** [TrezorTop/R6S-recoil-reducer#1]
Your project impressed me very much! This is so good!
I'm not good at English, sorry if it makes you confused.
I have question, can I put multiple "y" in setting.json for moving down sequentially in numerical order like this?
 
    "profile_1": {
      "x": 0,
      "y": 70, 60, 65, 65, 65, 70, 75, 75, 80, 80, 80, 80,
      "x_delay": 0,
      "y_delay": 0
    },
    
Thank you!

**Comment by TrezorTop** [comment]
No, this is not possible. This project is deprecated and won't get any updates. Maybe later I'll write a similar project that will support this feature

**Comment by imkrey** [comment]
Sorry, last question.
Status about detected by Battleye: R6S, PUBG?
